services:
  app:
    build: .
    container_name: qqfarm-app-${GIT_COMMIT:-latest}
    image: qqfarm-app-img:${GIT_COMMIT:-latest}
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qqfarm
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data
    restart: always

volumes:
  pgdata:
  redisdata:
